{{- if .Values.daemon.configFiles }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "lotus-aio.fullname" . }}-daemon-config
  labels:
    {{- include "lotus-aio.labels" . | nindent 4 }}
data:
{{- range $path, $config := .Values.daemon.configFiles }}
  {{ $path }}: |
{{ $config | indent 4 -}}
{{- end }}
{{- end }}
{{- if .Values.miner.configFiles }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "lotus-aio.fullname" . }}-miner-config
  labels:
    {{- include "lotus-aio.labels" . | nindent 4 }}
data:
{{- range $path, $config := .Values.miner.configFiles }}
  {{ $path }}: |
{{ $config | indent 4 -}}
{{- end }}
{{- end }}
{{- if .Values.worker.configFiles }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "lotus-aio.fullname" . }}-worker-config
  labels:
    {{- include "lotus-aio.labels" . | nindent 4 }}
data:
{{- range $path, $config := .Values.worker.configFiles }}
  {{ $path }}: |
{{ $config | indent 4 -}}
{{- end }}
{{- end }}
