{{- if .Values.configFiles }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "lotus-daemon.fullname" . }}-config
  labels:
    {{- include "lotus-daemon.labels" . | nindent 4 }}
data:
{{- range $path, $config := .Values.configFiles }}
  {{ $path }}: |
{{ $config | indent 4 -}}
{{- end }}
{{- end }}
