apiVersion: v1
kind: Service
metadata:
  name: {{ include "lotus-daemon.fullname" . }}
  labels:
    {{- include "lotus-daemon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "lotus-daemon.selectorLabels" . | nindent 4 }}
